### PR TITLE
Add "scroll" command, allowing efficient bulk pagination

### PR DESCRIPTION
**Pull request by praxxis**
See https://www.elastic.co/guide/en/elasticsearch/reference/0.90/search-request-scroll.html for details on the command itself

ping @cainlevy

### CODE REVIEW

**Comment by praxxis** [comment]
Really we should be returning some sort of `scrollable` object from the method, so you don't need to pass in index and types if you're paginating.

**Comment by cainlevy** [comment]
looks good! what do you think about offering convenience methods similar to activerecord's `find_in_batches` and `find_each`, too. i'm just not sure where to put them. this client library doesn't have precedent for that kind of abstraction, but it still feels like the right place.

**Comment by praxxis** [comment]
Yea I was going to put something analogous to `find_in_batches` them in `EsSearch::Search` in Rails, seeing as that's where we have a bunch of stuff already

**Comment by cainlevy** [comment]
should work out fine. my use case won't have access to a search object, but i'll be okay.

**Comment by tiegz** [comment]
:metal: :metal:

**Pull request merged**
